local MP = ...

return {
	{ "nvim-web-devicons" },
	{ import = MP:relpath("lsp") },
	{ import = MP:relpath("noice") },
	{ import = MP:relpath("colorschemes") },
	{ import = MP:relpath("snacks") },
	{ import = MP:relpath("treesitter") },
	{ import = MP:relpath("which-key") },
	{ import = MP:relpath("blink") },
	{ import = MP:relpath("cmp-cmdline") },
	{ import = MP:relpath("conform") },
	-- { import = MP:relpath("fidget") },
	{ import = MP:relpath("gitsigns") },
	{ import = MP:relpath("lualine") },
	{ import = MP:relpath("mason") },
	{ import = MP:relpath("nvim-lint") },
	{ import = MP:relpath("nvim-surround") },
	{ import = MP:relpath("startup-time") },
	{ import = MP:relpath("mini") },
	{ import = MP:relpath("trouble") },
	{ import = MP:relpath("telescope") },
	{ import = MP:relpath("nvim-notify") },
	{ import = MP:relpath("markview") },
	{ import = MP:relpath("moveline-nvim") },
	{ import = MP:relpath("persistence") },
	{ import = MP:relpath("rainbow-delimiters") },
	{ import = MP:relpath("nvim-autopairs") },
	{ import = MP:relpath("flash") },
	{ import = MP:relpath("bufferline") },
	{ import = MP:relpath("highlight-colors") },
	{ import = MP:relpath("todo-comments") },
}
